//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wihalik_backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class choice
    {
        public int id { get; set; }
        public string choice_label { get; set; }
        public Nullable<int> isAnswer { get; set; }
        public Nullable<int> question_id { get; set; }
    }
}
