//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wihalik_backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class episode
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<double> startTime { get; set; }
        public Nullable<int> season_Id { get; set; }
        public Nullable<System.DateTime> startedDateTime { get; set; }
        public Nullable<System.DateTime> endedDateTime { get; set; }
        public Nullable<int> timer_status { get; set; }
    }
}
