//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wihalik_backend.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Wiha_likiEntities : DbContext
    {
        public Wiha_likiEntities()
            : base("name=Wiha_likiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<answer_sms_mapping> answer_sms_mapping { get; set; }
        public virtual DbSet<episode> episodes { get; set; }
        public virtual DbSet<season> seasons { get; set; }
        public virtual DbSet<choice> choices { get; set; }
        public virtual DbSet<question> questions { get; set; }
        public virtual DbSet<register> registers { get; set; }
    }
}
